Implement Value Caching and Diffing for Optimized Change Detection
bramus/style-observer pull request #7
Opened 2024-09-04 17:23 UTC by faizanu94

This pull request introduces value caching and diffing mechanisms to optimize change detection. By caching previous values and diffing them against current values, we ensure that only the property that has changed is passed to the callback function as discussed in #1

Changes
- Added a value caching system to store previous state values
- Implemented a diffing algorithm to efficiently compare current values against cached values
- Modified callback functions to receive only the properties that have changed, based on the diffing results

2024-09-06 21:41 UTC, bramus commented
@faizanu94 I’m not sure if you are looking for a review yet or not, but here goes: the core of this PR looks really good.

The only thing that is missing is a flag to get back the old behavior, where an author can choose between getting only these `changedProperties` (default behavior) or getting back all the monitored properties.

The logic for that is similar to the flag you wrote in #1.

_(Once this PR is in, we can pick up #1 again to let users choose between the current simple format, or the more rich format)_

2024-09-06 22:41 UTC, faizanu94 commented
Thanks for the reminder about taking care of the old behavior - I’ve added the flag `observeAllProperties` to toggle between the old and new behaviors, and updated the README accordingly. All set now!

2024-09-09 19:31 UTC, bramus commented
> I’ve added the flag `observeAllProperties` to toggle between the old and new behaviors, and updated the README accordingly. All set now!

Instead of a `boolean` here, this needs to be the `{ callbackMode: CallbackMode.INDIVIDUAL }` that you introduced in #3. Maybe a better name would be `NotificationMode`.

2024-09-10 13:55 UTC, faizanu94 commented
Thanks for the feedback! I've replaced the boolean flag with `NotificationMode` as suggested, using `NotificationMode.INDIVIDUAL` and `NotificationMode.ALL`. This approach can easily scale to other options like `ReturnFormat` in the future. README has been updated accordingly

2024-09-14 20:51 UTC, bramus requested changes
This is looking great! In hindsight the `INDIVIDUAL` mode is incorrectly named, as it can report two changed properties at once.

I have made suggestions (which you can apply in the GitHub UI by simply clicking the button) to rename it to `CHANGED_ONLY`.

Also reworded the text in the README.

2024-09-14 20:51 UTC, bramus commented on README.md
> +* notificationMode (NotificationMode, default: INDIVIDUAL): Determines whether to observe and return all properties (ALL) or only the changed ones (INDIVIDUAL)
```suggestion
* `notificationMode` (`NotificationMode`, default: `CHANGED_ONLY`): Determines whether to pass all properties (`ALL`) or only the changed ones (`CHANGED_ONLY`) into the callback
```

2024-09-14 20:51 UTC, bramus commented on README.md
> +      notificationMode?: NotificationMode.INDIVIDUAL
```suggestion
      notificationMode?: NotificationMode.CHANGED_ONLY
```

2024-09-14 20:51 UTC, bramus commented on src/index.ts
> +}
```suggestion
export enum NotificationMode {
  CHANGED_ONLY = 'changed_only',
  ALL = 'all',
}
```

2024-09-14 20:51 UTC, bramus commented on src/index.ts
> +    this._notificationMode = options.notificationMode ?? NotificationMode.INDIVIDUAL;
```suggestion
    this._notificationMode = options.notificationMode ?? NotificationMode.CHANGED_ONLY;
```

2024-09-14 21:22 UTC, faizanu94 commented
Thanks for the suggestions - I’ve applied the changes. Appreciate the guidance!

2024-09-14 21:41 UTC, bramus approved these changes

2024-09-14 21:44 UTC, merged